- name: create users
  hosts: all
  become: true
  tasks:
    - name: create user
      user:
        name: tita
        shell: /bin/bash
        groups: devops,example
        append: yes
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa

    - name: Creating an empty file
      file:
         path: /etc/sudoers.d/tita
         state: touch

    - name: configure a pass-wordless authentication & execution for tita
      lineinfile:
        path: /etc/sudoers.d/tita
        line: "tita ALL=(ALL) NOPASSWD: ALL"
        state: present

    - name: install the SSH public key on managed host for tita
      authorized_key:
        user: tita
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
